name: server
description: A realtime chat server

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  shelf: ^0.7.9
  shelf_router: ^0.7.3
  shelf_web_socket: ^0.2.3
  json_rpc_2: ^2.2.2
  redux: ^4.0.0+3
  redux_thunk: ^0.3.0
  freezed_annotation: ^0.12.0
  web_socket_channel: ^1.1.0
  pedantic: ^1.9.0

dev_dependencies:
  shelf_router_generator: ^0.7.0+1
  freezed: ^0.12.2
  build_runner: ^1.10.4
  test: ^1.14.4
  mockito: ^4.1.3
