name: cli
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  json_rpc_2: ^2.2.2
  pedantic: ^1.9.0
  http: ^0.12.2
  web_socket_channel: ^1.1.0
  args: ^1.6.0
# dev_dependencies:
